### ISSUE TITLE
[REQUEST] Multiplayer

### ISSUE THREAD

**Issue by MrHuu** [masterfeizz/ioQuake3DS#6]
**Note:**
This is a feature request. With Quake III being all about deathmatch / tournament / multiplayer, fragging friends with the same handicap (3DS) would add a lot of value to this port.

**Issue:**
When selecting 'Multiplayer' in the main menu, the bottom screen gives the message: 

`Sys_SentPacket: bad address type`

From here, you can only press 'start' to quit the application.

**Comment by rebane2001** [comment]
Fully agreed

**Comment by masterfeizz** [comment]
I have released and new version which should fix the problem.
